version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
  
  build:
    commands:
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
  
  post_build:
    commands:
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo '[{"name":"akash-container","imageUri":"'$ECR_REPOSITORY_URI':'$IMAGE_TAG'"}]' > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json
